### PR TITLE
Feature/shaq foo

### PR DESCRIPTION
**Pull request by SSJohns**
## Purpose

Testing purposes

## Changes

Added test files

## Side effects

Nope

### CODE REVIEW

**Comment by Johnetordoff** [comment]
should also have test for forking and registering, as well setting to setting privacy and add contributors

**Comment by SSJohns** [comment]
I'm making more test now with the api libraries. I just wanted to commit the working part now before I broke anything.

**Comment by SSJohns** [comment]
Leave this for the weekend and I'll keep working on it. But now I doing file upload testing and api_test.

**Comment by Johnetordoff** [comment]
@SSJohns remember to test set parent node

**Comment by Johnetordoff** [comment]
This should also prevent adding citations, prevent embargoing, adding a wiki, adding an addon, setting a parent node, displaying an authors list and adding tags.

**Comment by Johnetordoff** [comment]
@SSJohns Great! now stop the failing tests and I'll merge.

**Pull request merged**
